# fly.toml app configuration file generated for quick-chat-app on 2023-06-24T21:45:11+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "quick-chat-app"
primary_region = "mad"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[mounts]
  destination = "/pb/pb_data"
  source = "pb_data"